/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.4.0/samples
 */
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    java
    id("com.gradleup.shadow") version "9.4.0"
}

group = providers.gradleProperty("group").get()
version = providers.gradleProperty("version").get()

val pluginVersion = version.toString()

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.92-stable")
    implementation("org.xerial:sqlite-jdbc:3.46.0.0")
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release.set(25)
}

tasks.named<ProcessResources>("processResources") {
    filteringCharset = "UTF-8"

    val props = mapOf("version" to pluginVersion)
    inputs.properties(props)

    filesMatching("plugin.yml") {
        expand(props)
    }
}

tasks.shadowJar {
    archiveBaseName.set("LikeBeacon")
    archiveClassifier.set("")
    mergeServiceFiles()
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

tasks.register<Copy>("deployToTestServer") {
    dependsOn(tasks.shadowJar)
    from(tasks.shadowJar.flatMap { it.archiveFile })
    from("src/main/resources/config.yml") {
        into("LikeBeacon")
    }
    into(file("./paper-test/plugins"))
}
